name: Terraform Apply

on: 
  schedule:
    - cron: '0 10 * * 2' # Every Tuesday at 6:00 PM (GMT +8)
    - cron: '0 10 * * 4' # Every Thursday at 6:00 PM (GMT +8)
    - cron: '0 1 * * 6'  # Every Saturday at 9:00 AM (GMT +8)

  workflow_dispatch:

env:            
  AWS_REGION: ap-southeast-1  

jobs:
  Apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Apply
      run: terraform apply -auto-approve